version: "3.9"
services:
  db:
    image: postgres:15
    container_name: gin_gorm_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: gin_gorm_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5431:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gin_gorm_app
    environment:
      DB_HOST: db
      DB_PORT: 5431
      DB_USER: admin
      DB_PASSWORD: 1q2w3e4r
      DB_NAME: gin_gorm_db
    depends_on:
      - db
    ports:
      - "8001:8080"
    volumes:
      - .:/app

volumes:
  db_data:
